- name: Setup gitconfig file
  template:
    src: templates/gitconfig.j2
    dest: /home/{{ username }}/.gitconfig
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Create git directory
  file:
    path: /home/{{ username }}/git
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory

- name: Clone dotfiles
  git:
    repo: git@github.com:soleblaze/dotfiles.git
    dest: /home/{{ username }}/git/dotfiles
    update: no
  become_user: "{{ username }}"

- name: Clone scripts
  git:
    repo: git@github.com:soleblaze/scripts.git
    dest: /home/{{ username }}/git/scripts
    update: no
  become_user: "{{ username }}"

- name: Clone dotfiles-private
  git:
    repo: git@bitbucket.org:soleblaze/dotfiles-private.git
    dest: /home/{{ username }}/git/dotfiles-private
    update: no
  become_user: "{{ username }}"

- name: Clone dotfiles-encrypted
  git:
    repo: git@bitbucket.org:soleblaze/dotfiles-encrypted.git
    dest: /home/{{ username }}/git/dotfiles-encrypted
    update: no
  become_user: "{{ username }}"
