- name: Install golang
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - golang

- name: Install libnotify
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - libnotify-bin

- name: Install zeal
  apt:
    name: zeal
    state: present
