- name: Install weechat
  apt:
    name: weechat
    state: present

- name: Create .weechat directory
  file:
    path: /home/{{ username }}/.weechat
    owner: "{{ username}}"
    group: "{{ username}}"
    state: directory

- name: Create symlinks for weechat configuration files
  file:
    src: /home/{{ username }}/git/dotfiles-private/weechat/{{ item }}
    dest: /home/{{ username }}/.weechat/{{ item }}
    owner: "{{ username}}"
    group: "{{ username}}"
    state: link
  with_items:
    - alias.conf
    - aspell.conf
    - buffers.conf
    - buflist.conf
    - charset.conf
    - exec.conf
    - fifo.conf
    - fset.conf
    - guile.conf
    - iset.conf
    - logger.conf
    - lua.conf
    - perl.conf
    - plugins.conf
    - python.conf
    - relay.conf
    - ruby.conf
    - script.conf
    - sec.conf
    - tcl.conf
    - trigger.conf
    - weechat.conf
    - xfer.conf

- name: Create symlink for irc.conf
  file:
    src: /home/{{ username }}/git/dotfiles-encrypted/config/irc.conf
    dest: /home/{{ username }}/.weechat/irc.conf
    owner: "{{ username}}"
    group: "{{ username}}"
    state: link
